# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- devel

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'ffmpeg'
  buildImage: $(imageName):build-$(build.buildId)
  fullImage: $(imageName):$(build.buildId)

steps:
- script: docker build --target=build -f Dockerfile -t $(buildImage) .
  displayName: 'create build image'
- script: docker build -f Dockerfile -t $(fullImage) .
  displayName: 'create full image'
- script: docker run -t $(fullImage) -buildconf
  displayName: 'validate built image'
- script: echo "##vso[task.setvariable variable=appversion;]$(cat VERSION)"
  displayName: 'set image version'
- script: |
    chmod +x version.sh
    docker login -u $(dockerId) -p $(dockerPassword)
    docker tag $(buildImage) $(dockerRepoId)/$(imageName):build-$(appversion)
    docker tag $(buildImage) $(dockerRepoId)/$(imageName):build-latest
    docker push $(dockerRepoId)/$(imageName):build-$(appversion)
    docker push $(dockerRepoId)/$(imageName):build-latest
    docker tag $(fullImage) $(dockerRepoId)/$(imageName):$(appversion)
    docker tag $(fullImage) $(dockerRepoId)/$(imageName):latest
    docker push $(dockerRepoId)/$(imageName):$(appversion)
    docker push $(dockerRepoId)/$(imageName):latest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'push image to dockerhub'
